### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by TheRedSpy15**
I simply ran `flutter pub upgrade --major-versions`

Not sure if the generated files should be modified. But they were automatically

Largely needed to upgrade the `http` package as the current version is rather dated

### CODE REVIEW

**Comment by TheRedSpy15** [comment]
Not sure about the CLA, this repo doesn't have anything idicating it's a Google repo

**Comment by M97Chahboun** [comment]
Thanks @TheRedSpy15 We will upgrade all packages ASAP.

**Review by M97Chahboun — CHANGES_REQUESTED** [review]
Please add follow junk files to gitignore 
- example/linux/flutter/generated_plugin_registrant.cc
- example/linux/flutter/generated_plugins.cmake
- example/macos/Flutter/GeneratedPluginRegistrant.swift
- example/pubspec.lock

**Comment by M97Chahboun** [comment]
@TheRedSpy15 
If you are not currently covered under a CLA, please visit https://cla.developers.google.com/

**Comment by TheRedSpy15** [comment]
> @TheRedSpy15 If you are not currently covered under a CLA, please visit https://cla.developers.google.com/

I signed the CLA and added the files to the gitignore

**Review by M97Chahboun — APPROVED** [review]

**Comment by M97Chahboun** [comment]
LGTM

**Pull request merged**
